name: Tests Back And Front

on:
  pull_request:   # Lancer les tests sur une PR avant validation
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd back
          mvn clean install
          cd ../front
          npm ci

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.0
        with:
          coverage_results_path: back/target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 80
          fail_below_threshold: false
          publish_only_summary: false
          
      # uploads the coverage-report.md artifact  # Optional
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/

      - name: Build Backend
        working-directory: back
        run: mvn clean install -DskipTests

      - name: SonarQube Scan Back
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
          
      - name: Run tests with Karma
        run: |
          cd front
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Upload Karma coverage report
        uses: actions/upload-artifact@v4
        with:
          name: karma-coverage-report
          path: front/coverage/bobapp/

      - name: SonarQube Scan Front
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'
